name: Elixir CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1"
          elixir-version: "1.17.3"

      - name: Install dependencies
        run: mix deps.get

      - name: Run tests
        env:
          MIX_ENV: test
        run: mix test
